name: Builds

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: Checkout
        run: echo ${{ github.ref }}
